### ISSUE TITLE
Releases unoptimized

### ISSUE THREAD

**Issue by TraGicCode** [LeadPipeSoftware/LeadPipe.Net#4]
Opening up the published nuget package and viewing the .NET Assemblies i noticed that they are being built /w the debug build configuration instead of release which prevents optimizations from being applied. @gregmajor 

![image](https://cloud.githubusercontent.com/assets/6224270/15745569/1176e6f2-2898-11e6-9e20-c2ed50a7cee2.png)

**Comment by gregmajor** [comment]
Good catch, @TraGicCode. I'm working on moving to Appveyor and publishing the NuGet packages in release mode from there.

**Comment by TraGicCode** [comment]
Any update?
